version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: gwala

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongodb:27017/
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

volumes:
  mongodb-data:
    name: mongodb-data
